from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
LOG_DIR = BASE_DIR / "logs"
DB_PATH = DATA_DIR / "quant_bot.db"
STATE_PATH = DATA_DIR / "state.json"
ERROR_LOG_PATH = LOG_DIR / "error.log"

INITIAL_CASH = 10_000.0
TIMEFRAME = "1h"
KLINE_LIMIT = 200
LOOP_SLEEP_SECONDS = 60
MAX_CYCLES = 1

EXECUTION_MODE = "paper"
SLIPPAGE_RATE = 0.0005
FEE_RATE = 0.0004

MAX_TOTAL_MARGIN_RATIO = 0.30
MAX_LEVERAGE = 3
MAX_DRAWDOWN = 0.10
MAX_DAILY_LOSS = 0.05
MAX_CONSECUTIVE_LOSSES = 3
MIN_RECENT_WIN_RATE = 0.30
RECENT_TRADE_WINDOW = 10
ABNORMAL_VOLATILITY_MULTIPLIER = 3.0

BINANCE_FUTURES_TESTNET_REST_URL = "https://demo-fapi.binance.com"

